version: '3'
services:
  # ~~~~ user server setup ~~~~ #
  mysql-users:
    container_name: user-sql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./sql/sql-users:/docker-entrypoint-initdb.d/
    networks:
      - mynet

  user-management-api:
    container_name: user-management-api
    build: ./user-management-api
    env_file: ./user-management-api/.env
    depends_on:
      - mysql-users
    networks:
      - mynet
    ports:
      - "5002:5002"

  # ~~~~ data server setup ~~~~ #
  mysql-quack:
    container_name: quack-sql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./sql/sql-quack:/docker-entrypoint-initdb.d/
    networks:
      - mynet

  server-data:
    container_name: server-data
    build: ./server-data
    env_file: ./server-data/.env
    volumes:
      - ./server-data/backend-data:/app/backend-data
      - ./server-data/frontend-data:/app/frontend-data
    depends_on:
      - mysql-quack
    networks:
      - mynet
    ports:
      - "80:80"

  # ~~~ TOTP authenticator ~~~~ #
  authenticator:
    container_name: authenticator
    build: ./authenticator
    environment:
      - TOTPSECRET=secrety-secret
    volumes:
      - ./authenticator:/app
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
