version: '3'
services:
  # ~~~~ user server setup ~~~~ #
  mysql-users:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./sql/sql-users:/docker-entrypoint-initdb.d/

  user-management-api:
    build: ./user-management-api
    environment:
      - HOST=0.0.0.0
      - PORT=5002
      - MYSQLHOST=mysql-users
      - MYSQLUSER=root
      - MYSQLPASS=example
      - PEPPER=802A
      - TOTPSECRET=secretysecret
      - JWTSECRET=othersecretysecret
    #volumes:
      #- ./user-management-api:/app
    ports:
      - "5002:5002"
    depends_on:
      - mysql-users

  # ~~~~ data server setup ~~~~ #
  mysql-quack:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql/sql-quack:/docker-entrypoint-initdb.d/

  server-data:
    build: ./servers/server-data
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=mysql-quack
      - MYSQLUSER=root
      - MYSQLPASS=example
    volumes:
      - ./servers/server-data/backend-data:/app/backend-data
      - ./servers/server-data/frontend-data:/app/frontend-data
    ports:
      - "80:80"
    depends_on:
      - mysql-quack

  # ~~~ TOTP authenticator ~~~~ #
  authenticator:
    build: ./authenticator
    environment:
      - TOTPSECRET=secretysecret
    volumes:
      - ./authenticator:/app
