version: '3'
services:
  # ~~~~ user server setup ~~~~ #
  mysql-users:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./sql/sql-users:/docker-entrypoint-initdb.d/
    networks:
      - mynet

  user-management-api:
    container_name: user-management-api
    build: ./user-management-api
    environment:
      - HOST=0.0.0.0
      - PORT=5002
      - MYSQLHOST=mysql-users
      - MYSQLUSER=root
      - MYSQLPASS=example
      - PEPPER=802A
      - TOTPSECRET=secretysecret
      - JWTSECRET=othersecretysecret
    depends_on:
      - mysql-users
    networks:
      - mynet
    ports:
      - "5002:5002"

  # ~~~~ data server setup ~~~~ #
  mysql-quack:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./sql/sql-quack:/docker-entrypoint-initdb.d/
    networks:
      - mynet

  server-data:
    container_name: server-data
    build: ./servers/server-data
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - MYSQLHOST=mysql-quack
      - MYSQLUSER=root
      - MYSQLPASS=example
      - JWTSECRET=your_secret_key
    volumes:
      - ./servers/server-data/backend-data:/app/backend-data
      - ./servers/server-data/frontend-data:/app/frontend-data
    depends_on:
      - mysql-quack
    networks:
      - mynet
    ports:
      - "80:80"

  # ~~~ TOTP authenticator ~~~~ #
  authenticator:
    build: ./authenticator
    environment:
      - TOTPSECRET=secretysecret
    volumes:
      - ./authenticator:/app
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
